[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "about"
    name = "Acerca de"
    url = "/about"
    weight = 2

[[main]]
    identifier = "tags"
    name = "Etiquetas"
    url = "/tags"
    weight = 4

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/Roj"
    weight = 3